# Generated by Django 5.0.3 on 2024-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criancaespecial',
            name='endereço',
            field=models.CharField(default='Insira um endereço', max_length=200),
        ),
        migrations.AddField(
            model_name='criancaespecial',
            name='responsavel',
            field=models.CharField(default='Insira um Nome', max_length=100),
        ),
        migrations.AddField(
            model_name='criancaespecial',
            name='telefone',
            field=models.CharField(default='Insira um telefone', max_length=80),
        ),
    ]
