# Generated by Django 4.2.3 on 2024-04-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_criancaespecial_endereço_criancaespecial_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criancaespecial',
            name='email',
            field=models.EmailField(default='seunome@instituição.com.br', max_length=200),
        ),
    ]
