# Generated by Django 5.0.6 on 2024-05-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_alter_missao_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='static/imagens')),
            ],
        ),
        migrations.AlterField(
            model_name='missao',
            name='imagem',
            field=models.ImageField(upload_to='static/imagens'),
        ),
    ]
