# Generated by Django 5.0.6 on 2024-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0007_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='Observacoes',
            field=models.TextField(default='Sem observações'),
        ),
    ]
