# Generated by Django 4.2 on 2024-05-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0008_contato_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='Observacoes',
            field=models.TextField(default='Sem observações', null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='email',
            field=models.EmailField(default='seunome@instituição.com.br', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='endereço',
            field=models.CharField(default='Insira um endereço', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='idade',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='responsavel',
            field=models.CharField(default='Insira um Nome', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='telefone',
            field=models.CharField(default='Insira um telefone', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='missao',
            name='imagem',
            field=models.ImageField(null=True, upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='missao',
            name='texto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='missao',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='valorimage',
            name='imagem',
            field=models.ImageField(null=True, upload_to='static/imagens'),
        ),
    ]
