# Generated by Django 4.2 on 2024-05-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0009_alter_contato_observacoes_alter_contato_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='Observacoes',
            new_name='observacoes',
        ),
        migrations.RenameField(
            model_name='criancaespecial',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.AddField(
            model_name='missao',
            name='descricao_imagem',
            field=models.CharField(default='Insira a descrição da necessidade', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(default='Insira seu Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='Insira seu Nome', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default='Insira um telefone', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='descricao',
            field=models.TextField(default='Insira a descrição da necessidade', null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='idade',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='criancaespecial',
            name='nome',
            field=models.CharField(default='Insira seu Nome', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='missao',
            name='texto',
            field=models.TextField(default='Insira um texto', null=True),
        ),
        migrations.AlterField(
            model_name='missao',
            name='titulo',
            field=models.CharField(default='Insira um Título', max_length=200, null=True),
        ),
    ]
