# Generated by Django 4.2 on 2024-09-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0011_evento_membro_noticia_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='historias/')),
            ],
        ),
    ]
